name: Workflow for Pushes

on: 
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build react
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: 'frontend-web'
    - uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --immutable ${{ inputs.flags }}
      shell: bash
    - name: Build
      run: |
        yarn
        yarn build
