on: 
  push

jobs:
  build:
    name: Build react
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DerYeger/yarn-setup-action@v2.0.21
      with:
        node-version: 16
    - name: Build
      run: |
        yarn
        yarn build
