name: Workflow for Pushes

on: 
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build react
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mskelton/setup-yarn@v2.0.0
      with:
        node-version: 16
    - name: Build
      run: |
        cd frontend-web
        yarn
        yarn build
