on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:
  pull_request:
    types: [opened]
  push:

jobs:
  analyse:
    name: 'Analyse the code quality'
    runs-on: ubuntu-latest
    env:
      env_secret: ${{ secrets.test_secret }}

    steps:
#      - name: 'Analysing code with CodeQL'
#        uses: github/codeql-action/init@v3
#        with:
#          languages: 'javascript'
      - run: |
          echo test secreto: ${{ secrets.TEST_SECRET }}
      - if: ${{ env.env_secret == 'valor errado' }}
        run: |
          echo '::notice::secrete ok'
          echo '::warning::secrete ' ${{ env.env_secret }}
      - if: ${{ cancelled() }}
        run: echo '::error::secrete not valid'
