on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:
  pull_request:
    types: [opened]
  push:

jobs:
  analyse:
    name: 'Analyse the code quality'
    runs-on: ubuntu-latest

    steps:
#      - name: 'Analysing code with CodeQL'
#        uses: github/codeql-action/init@v3
#        with:
#          languages: 'javascript'
      - run: |
          echo test secreto: ${{ secrets.TEST_SECRET }} 
