on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:
  pull_request:
    types: [opened]
  push:

jobs:
  analyse:
    name: 'Analyse the code quality'
    runs-on: ubuntu-latest
    env:
      env_secret: ${{ secrets.test_secret }}

    steps:
#      - name: 'Analysing code with CodeQL'
#        uses: github/codeql-action/init@v3
#        with:
#          languages: 'javascript'
      - run: |
          echo test secreto: ${{ secrets.TEST_SECRET }}
      - if: ${{ env.env_secret == 'valor errado' }}
        id: validate
        run: |
          echo '::notice::secrete ok'
          echo '::warning::secrete ' ${{ env.env_secret }}
      - if: ${{ steps.validate.conclusion == 'skipped' }}
        run: echo '::error::secrete not valid'
      - run: echo ${{ steps.validate.conclusion }}
  scripts:
    name: 'Run script from repo'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    outputs:
      chave1: ${{ steps.script.outputs.chave2 }}
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x script-test.sh
      - run: ./script-test.sh ${{ github.actor }}
      - run: echo "chave2=$(sh script-test.sh $GITHUB_ACTOR)" >> $GIHUB_OUTPUT
        id: script
  results:
    runs-on: ubuntu-latest
    needs:
      - scripts
    steps:
      - run: echo "test-output='valor do output'" >> $GITHUB_OUTPUT
        id: set-value
      - run: echo "teste de passagem de valor entre steps:" ${{ steps.set-value.outputs.test-output }}
      - run: echo "teste de passagem de valor entre jobs:" ${{ needs.scripts.outputs.chave1 }}

