on:
  schedule:
    - cron: '5 * * * *'

jobs:
  analyse:
    name: 'Analyse the code quality'
    runs-on: ubuntu-latest

    steps:
      - name: 'Analysing code with CodeQL'
        uses: actions/codeql-action@v3
        with:
          languages: 'javascript'
